// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEJc6Sl7gweMNPm2OVkyz6A7Vwx1YiCC0',
    appId: '1:1058281973456:android:a08880d3320c95df06e0d5',
    messagingSenderId: '1058281973456',
    projectId: 'phista-81bf8',
    databaseURL: 'https://phista-81bf8-default-rtdb.firebaseio.com',
    storageBucket: 'phista-81bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Lpm-_B562IxeU9WTI95RmyVztcgtcQs',
    appId: '1:1058281973456:ios:67a7f2274603b9fc06e0d5',
    messagingSenderId: '1058281973456',
    projectId: 'phista-81bf8',
    databaseURL: 'https://phista-81bf8-default-rtdb.firebaseio.com',
    storageBucket: 'phista-81bf8.firebasestorage.app',
    androidClientId: '1058281973456-0of5ifq5t999mjsvqea7i6b4alukha62.apps.googleusercontent.com',
    iosClientId: '1058281973456-jvne9uioi99odbomprnaobetaa8vju3h.apps.googleusercontent.com',
    iosBundleId: 'com.phista.ios',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAvMQy6a2ZwU60Yg43NfIhTfz7rZE6bTSY",
      authDomain: "phista-81bf8.firebaseapp.com",
      databaseURL: "https://phista-81bf8-default-rtdb.firebaseio.com",
      projectId: "phista-81bf8",
      storageBucket: "phista-81bf8.firebasestorage.app",
      messagingSenderId: "1058281973456",
      appId: "1:1058281973456:web:fcbb6159d107e5ab06e0d5",
      measurementId: "G-KTPZQQSE7R"
  );
}
